### ISSUE TITLE
Migrations are failing

### ISSUE THREAD

**Issue by muhlba91** [padhi-homelab/docker_unms#1]
Hi,

I have followed https://github.com/padhi-homelab/services/tree/master/unms to setup UNMS but when starting up it fails due to migration errors in UNMS.

Logs from the UNMS container:
```
yarn run v1.22.4
warning Skipping preferred cache folder "/home/app/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ yarn backup:apply && yarn migrate && yarn check-crm-db
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"
warning Skipping preferred cache folder "/home/app/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ node ./cli/apply-backup.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"
warning Skipping preferred cache folder "/home/app/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ node ./cli/migrate.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"
Extension 'uuid-ossp:1.1 installed.
Extension 'pgcrypto:1.3 installed.
Extension 'cube:1.4 installed.
Extension 'earthdistance:1.1 installed.
Extension 'unaccent:1.1 installed.
== 20170116111143-init.js (1.0.0): migrating =======
== 20170116111143-init.js: migrated (0.187s)
== 20170130091406-add-log-type.js (1.0.0): migrating =======
== 20170130091406-add-log-type.js: migrated (0.047s)
== 20170201081955-user-login-fail.js (1.0.0): migrating =======
== 20170201081955-user-login-fail.js: migrated (0.03s)
== 20170208134500-import-mongo.js (1.0.0): migrating =======
== 20170208134500-import-mongo.js: migrated (0.011s)
== 20170210131830-add-event-notif-fail.js (1.0.0): migrating =======
== 20170210131830-add-event-notif-fail.js: migrated (0.026s)
== 20170215091017-discovery.js (1.0.0): migrating =======
== 20170215091017-discovery.js: migrated (0.241s)
== 20170221112848-discover-ip-range.js (1.0.0): migrating =======
== 20170221112848-discover-ip-range.js: migrated (0.057s)
== 20170223104646-discover-drop-flags.js (1.0.0): migrating =======
== 20170223104646-discover-drop-flags.js: migrated (0.039s)
== 20170227100522-discovery-connect.js (1.0.0): migrating =======
== 20170227100522-discovery-connect.js: migrated (0.265s)
== 20170302145159-discovery-optimization.js (1.0.0): migrating =======
== 20170302145159-discovery-optimization.js: migrated (0.275s)
== 20170308144649-discovery-csv.js (1.0.0): migrating =======
== 20170308144649-discovery-csv.js: migrated (0.257s)
== 20170411101729-task.js (1.0.0): migrating =======
== 20170411101729-task.js: migrated (0.221s)
== 20170502104724-upgrade-logging.js (1.0.0): migrating =======
== 20170502104724-upgrade-logging.js: migrated (0.922s)
== 20170503083211-mac-aes-key.js (1.0.0): migrating =======
== 20170503083211-mac-aes-key.js: migrated (0.061s)
== 20170511153352-aes-key-update.js (1.0.0): migrating =======
== 20170511153352-aes-key-update.js: migrated (0.059s)
== 20170511160411-discovery.js (1.0.0): migrating =======
== 20170511160411-discovery.js: migrated (0.295s)
== 20170515064532-remove-customSmtpSslEnabled-key.js (1.0.0): migrating =======
== 20170515064532-remove-customSmtpSslEnabled-key.js: migrated (0.027s)
== 20170525124803-discovery-preferences.js (1.0.0): migrating =======
== 20170525124803-discovery-preferences.js: migrated (0.15s)
== 20170526114732-add-table-config-to-user.js (1.0.0): migrating =======
== 20170526114732-add-table-config-to-user.js: migrated (0.048s)
== 20170601112106-cleanup-statistics.js (1.0.0): migrating =======
== 20170601112106-cleanup-statistics.js: migrated (0.036s)
== 20170601112107-fix-statistics.js (1.0.0): migrating =======
== 20170601112107-fix-statistics.js: migrated (0.282s)
== 20170602095030-discovery.js (1.0.0): migrating =======
== 20170602095030-discovery.js: migrated (0.191s)
== 20170602124054-amend-table-config-to-user.js (1.0.0): migrating =======
== 20170602124054-amend-table-config-to-user.js: migrated (0.033s)
== 20170605143239-add-columns-table-editor.js (1.0.0): migrating =======
== 20170605143239-add-columns-table-editor.js: migrated (0.034s)
== 20170612062812-remove-table-config.js (1.0.0): migrating =======
== 20170612062812-remove-table-config.js: migrated (0.03s)
== 20170612100757-add-column-exchange-status-to-mac-aes-key.js (1.0.0): migrating =======
== 20170612100757-add-column-exchange-status-to-mac-aes-key.js: migrated (0.076s)
== 20170619084700-parse-nms-hostmane.js (1.0.0): migrating =======
== 20170619084700-parse-nms-hostmane.js: migrated (0.047s)
== 20170621122610-fix-statistics.js (1.0.0): migrating =======
== 20170621122610-fix-statistics.js: migrated (0.037s)
== 20170703121244-add-device-connection-fail.js (1.0.0): migrating =======
== 20170703121244-add-device-connection-fail.js: migrated (0.022s)
== 20170711115632-add-table-device-metadata.js (1.0.0): migrating =======
== 20170711115632-add-table-device-metadata.js: migrated (0.062s)
== 20170720104423-add_device_restart_timestamp.js (1.0.0): migrating =======
== 20170720104423-add_device_restart_timestamp.js: migrated (0.055s)
== 20170721114414-add-ip-address-table-config.js (1.0.0): migrating =======
== 20170721114414-add-ip-address-table-config.js: migrated (0.151s)
== 20170728132635-add-device-metadata-alias-note.js (1.0.0): migrating =======
== 20170728132635-add-device-metadata-alias-note.js: migrated (0.076s)
== 20170731162544-push-notifications.js (1.0.0): migrating =======
== 20170731162544-push-notifications.js: migrated (0.083s)
== 20170801101309-add-device-metadata-per-device.js (1.0.0): migrating =======
== 20170801101309-add-device-metadata-per-device.js: migrated (0.028s)
== 20170802084022-add-table-data-link.js (1.0.0): migrating =======
== 20170802084022-add-table-data-link.js: migrated (0.097s)
== 20170802115812-add-nms-outages-settings.js (1.0.0): migrating =======
== 20170802115812-add-nms-outages-settings.js: migrated (0.028s)
== 20170811083251-add-locale-to-nms.js (1.0.0): migrating =======
== 20170811083251-add-locale-to-nms.js: migrated (0.026s)
== 20170811121424-fix-google-maps-api-key.js (1.0.0): migrating =======
== 20170811121424-fix-google-maps-api-key.js: migrated (0.036s)
== 20170816105923-add-email-dispatch-fail-type.js (1.0.0): migrating =======
== 20170816105923-add-email-dispatch-fail-type.js: migrated (0.019s)
== 20170821110807-users-to-pgsql.js (1.0.0): migrating =======
== 20170821110807-users-to-pgsql.js: migrated (0.096s)
== 20170821135826-users-to-pgsql-data-migration.js (1.0.0): migrating =======
== 20170821135826-users-to-pgsql-data-migration.js: migrated (0.026s)
== 20170823103703-clean-non-existent-devices-data.js (1.0.0): migrating =======
== 20170823103703-clean-non-existent-devices-data.js: migrated (0.173s)
== 20170825083420-remove-allow-self-signed-certificate.js (1.0.0): migrating =======
== 20170825083420-remove-allow-self-signed-certificate.js: migrated (0.027s)
== 20170911190252-clean-device-metadata.js (1.0.0): migrating =======
== 20170911190252-clean-device-metadata.js: migrated (0.029s)
== 20170919153400-remove-ssldomain-key.js (1.0.0): migrating =======
== 20170919153400-remove-ssldomain-key.js: migrated (0.023s)
== 20171002135747-add_mac_aes_key_last_seen.js (1.0.0): migrating =======
== 20171002135747-add_mac_aes_key_last_seen.js: migrated (0.095s)
== 20171006113121-rename-olt-to-onu.js (1.0.0): migrating =======
== 20171006113121-rename-olt-to-onu.js: migrated (0.026s)
== 20171010130055-osm-googlemaps-picker.js (1.0.0): migrating =======
== 20171010130055-osm-googlemaps-picker.js: migrated (0.032s)
== 20171025090132-add_sites_to_pg.js (1.0.0): migrating =======
== 20171025090132-add_sites_to_pg.js: migrated (0.258s)
== 20171030150350-save-aes-key-as-buffer.js (1.0.0): migrating =======
== 20171030150350-save-aes-key-as-buffer.js: migrated (0.055s)
== 20171115114322-add-column-last_news_seen_date-migration.js (1.0.0): migrating =======
== 20171115114322-add-column-last_news_seen_date-migration.js: migrated (0.034s)
== 20171201132836-add-device-site-relation-pg-table.js (1.0.0): migrating =======
== 20171201132836-add-device-site-relation-pg-table.js: migrated (0.052s)
== 20171206133641-add-all-macs-and-all-ips-columns-to-discovery.js (1.0.0): migrating =======
== 20171206133641-add-all-macs-and-all-ips-columns-to-discovery.js: migrated (0.068s)
== 20171208140924-add-unsupported-onu-logtypeenum.js (1.0.0): migrating =======
== 20171208140924-add-unsupported-onu-logtypeenum.js: migrated (0.026s)
== 20171228090149-add-column-uptime-to-discovery-device.js (1.0.0): migrating =======
== 20171228090149-add-column-uptime-to-discovery-device.js: migrated (0.026s)
== 20180207095543-backup-types.js (1.0.0): migrating =======
== 20180207095543-backup-types.js: migrated (0.044s)
== 20180216083123-change-ip-column-to-cidr-type.js (1.0.0): migrating =======
== 20180216083123-change-ip-column-to-cidr-type.js: migrated (0.076s)
== 20180226075652-change-elevation-type-to-real.js (1.0.0): migrating =======
== 20180226075652-change-elevation-type-to-real.js: migrated (0.034s)
== 20180226121559-change-image-site-relation.js (1.0.0): migrating =======
== 20180226121559-change-image-site-relation.js: migrated (0.029s)
== 20180307174239-device-site.js (1.0.0): migrating =======
== 20180307174239-device-site.js: migrated (0.097s)
== 20180412074751-tasks.js (1.0.0): migrating =======
== 20180412074751-tasks.js: migrated (0.12s)
== 20180418133455-default-auto-profile.js (1.0.0): migrating =======
== 20180418133455-default-auto-profile.js: migrated (0.029s)
== 20180419100346-optimize_indexes.js (1.0.0): migrating =======
== 20180419100346-optimize_indexes.js: migrated (0.084s)
== 20180419125306-add-version-table.js (1.0.0): migrating =======
== 20180419125306-add-version-table.js: migrated (0.055s)
== 20180420091917-add-preferences-column.js (1.0.0): migrating =======
== 20180420091917-add-preferences-column.js: migrated (0.031s)
== 20180430132856-sort-tasks-migration.js (1.0.0): migrating =======
== 20180430132856-sort-tasks-migration.js: migrated (0.031s)
== 20180503113907-transmission-profile.js (1.0.0): migrating =======
== 20180503113907-transmission-profile.js: migrated (0.034s)
== 20180516085515-netflow.js (1.0.0): migrating =======
== 20180516085515-netflow.js: migrated (0.131s)
== 20180518101200-subnet.js (1.0.0): migrating =======
== 20180518101200-subnet.js: migrated (0.044s)
== 20180524101200-add-maintenance-mode-flag.js (1.0.0): migrating =======
== 20180524101200-add-maintenance-mode-flag.js: migrated (0.03s)
== 20180615031855-add-client-id-to-netflow.js (1.0.0): migrating =======
== 20180615031855-add-client-id-to-netflow.js: migrated (0.047s)
== 20180622091557-add-default-subnets.js (1.0.0): migrating =======
== 20180622091557-add-default-subnets.js: migrated (0.01s)
== 20180711035336-netflow-source.js (1.0.0): migrating =======
== 20180711035336-netflow-source.js: migrated (0.056s)
== 20180719102211-device-to-pg.js (1.0.0): migrating =======
== 20180719102211-device-to-pg.js: migrated (0.369s)
== 20180719124113-fix-outages-and-logs.js (1.0.0): migrating =======
== 20180719124113-fix-outages-and-logs.js: migrated (0.146s)
== 20180719125936-discovery.js (1.0.0): migrating =======
== 20180719125936-discovery.js: migrated (0.059s)
== 20180719130819-data-links.js (1.0.0): migrating =======
== 20180719130819-data-links.js: migrated (0.196s)
== 20180801063317-blackbox-devices.js (1.0.0): migrating =======
== 20180801063317-blackbox-devices.js: migrated (0.086s)
== 20180806023130-firmware-upgrade.js (1.0.0): migrating =======
== 20180806023130-firmware-upgrade.js: migrated (0.206s)
== 20180806110732-gps-to-decimals.js (1.0.0): migrating =======
== 20180806110732-gps-to-decimals.js: migrated (0.265s)
== 20180814043901-assoc-ups-device-role-to-transmission-freq.js (1.0.0): migrating =======
== 20180814043901-assoc-ups-device-role-to-transmission-freq.js: migrated (0.03s)
== 20180814114335-add-ospf-enabled-prop.js (1.0.0): migrating =======
== 20180814114335-add-ospf-enabled-prop.js: migrated (0.022s)
== 20180824040219-revert-statistics.js (1.0.0): migrating =======
== 20180824040219-revert-statistics.js: migrated (0.032s)
== 20180903110327-fix-statistics.js (1.0.0): migrating =======
== 20180903110327-fix-statistics.js: migrated (0.062s)
== 20180906025618-add_locate_running_column.js (1.0.0): migrating =======
== 20180906025618-add_locate_running_column.js: migrated (0.056s)
== 20180911040425-fix-data-links-view.js (1.0.0): migrating =======
== 20180911040425-fix-data-links-view.js: migrated (0.153s)
== 20180912024602-interface-name-in-logs.js (1.0.0): migrating =======
== 20180912024602-interface-name-in-logs.js: migrated (0.028s)
== 20180913035909-device-backups.js (1.0.0): migrating =======
== 20180913035909-device-backups.js: migrated (0.023s)
== 20180913104354-add-user-flag-secret-deciphered.js (1.0.0): migrating =======
== 20180913104354-add-user-flag-secret-deciphered.js: migrated (0.022s)
== 20180914013739-fix-airfiber-statistics.js (1.0.0): migrating =======
== 20180914013739-fix-airfiber-statistics.js: migrated (0.678s)
== 20180914062307-disable-letsencrypt-with-custom-cert.js (1.0.0): migrating =======
== 20180914062307-disable-letsencrypt-with-custom-cert.js: migrated (0.037s)
== 20180918095006-vault.js (1.0.0): migrating =======
== 20180918095006-vault.js: migrated (0.078s)
== 20180918101910-interface-addresses-optimization.js (1.0.0): migrating =======
== 20180918101910-interface-addresses-optimization.js: migrated (0.057s)
== 20180918113859-add-ucrm-enabled-settings-option.js (1.0.0): migrating =======
== 20180918113859-add-ucrm-enabled-settings-option.js: migrated (0.044s)
== 20180926011249-rename-airmax-models.js (1.0.0): migrating =======
== 20180926011249-rename-airmax-models.js: migrated (0.019s)
== 20180926024312-add-device-custom-ip-column.js (1.0.0): migrating =======
== 20180926024312-add-device-custom-ip-column.js: migrated (0.022s)
== 20181003100454-link-logs-to-outages.js (1.0.0): migrating =======
== 20181003100454-link-logs-to-outages.js: migrated (0.065s)
== 20181005014504-add-unknown-devices-table.js (1.0.0): migrating =======
== 20181005014504-add-unknown-devices-table.js: migrated (0.072s)
== 20181010010450-rename-onu-models.js (1.0.0): migrating =======
== 20181010010450-rename-onu-models.js: migrated (0.022s)
== 20181010011238-add-device-column-upgradable.js (1.0.0): migrating =======
== 20181010011238-add-device-column-upgradable.js: migrated (0.029s)
== 20181010093418-delete-unsupported-onu-logs.js (1.0.0): migrating =======
== 20181010093418-delete-unsupported-onu-logs.js: migrated (0.019s)
== 20181010095004-ensure-device-mac-uindex.js (1.0.0): migrating =======
== 20181010095004-ensure-device-mac-uindex.js: migrated (0.052s)
== 20181011083012-data-link-delete-on-interface-delete.js (1.0.0): migrating =======
== 20181011083012-data-link-delete-on-interface-delete.js: migrated (0.043s)
== 20181012040247-add-primary-key-to-netflow-tables.js (1.0.0): migrating =======
== 20181012040247-add-primary-key-to-netflow-tables.js: migrated (0.063s)
== 20181015112659-fix-device-stations.js (1.0.0): migrating =======
== 20181015112659-fix-device-stations.js: migrated (0.052s)
== 20181023105041-add-model-name-for-blackbox.js (1.0.0): migrating =======
== 20181023105041-add-model-name-for-blackbox.js: migrated (0.027s)
== 20181024090000-fix-unms-hostname.js (1.0.0): migrating =======
== 20181024090000-fix-unms-hostname.js: migrated (0.157s)
== 20181024093443-move-settings-to-postgres.js (1.0.0): migrating =======
== 20181024093443-move-settings-to-postgres.js: migrated (0.084s)
== 20181025014303-rename-airfiber-interfaces.js (1.0.0): migrating =======
== 20181025014303-rename-airfiber-interfaces.js: migrated (0.016s)
== 20181025100036-add-role-on-device.js (1.0.0): migrating =======
== 20181025100036-add-role-on-device.js: migrated (0.024s)
== 20181029114755-disable-upgradable-for-blackbox.js (1.0.0): migrating =======
== 20181029114755-disable-upgradable-for-blackbox.js: migrated (0.012s)
== 20181031100554-device-import.js (1.0.0): migrating =======
== 20181031100554-device-import.js: migrated (0.094s)
== 20181105121159-add-session-timeout-column.js (1.0.0): migrating =======
== 20181105121159-add-session-timeout-column.js: migrated (0.048s)
== 20181109111526-fix-data-link-generated-exclude-vlans.js (1.0.0): migrating =======
== 20181109111526-fix-data-link-generated-exclude-vlans.js: migrated (0.147s)
== 20181112121752-move-clients-from-clients.js (1.0.0): migrating =======
== 20181112121752-move-clients-from-clients.js: migrated (0.016s)
== 20181114010122-add-ucrm-bind-column.js (1.0.0): migrating =======
== 20181114010122-add-ucrm-bind-column.js: migrated (0.032s)
== 20181119090521-add-earthdistance-and-cube-extensions.js (1.0.0): migrating =======
== 20181119090521-add-earthdistance-and-cube-extensions.js: migrated (0.015s)
== 20181119105426-add-site-column-updated-at.js (1.0.0): migrating =======
== 20181119105426-add-site-column-updated-at.js: migrated (0.034s)
== 20181123095816-fix-sfp-vlans.js (1.0.0): migrating =======
== 20181123095816-fix-sfp-vlans.js: migrated (0.032s)
== 20181125074204-rename-discovery-metadata.js (1.0.0): migrating =======
== 20181125074204-rename-discovery-metadata.js: migrated (0.031s)
== 20181126013131-fix-datalink-ordering.js (1.0.0): migrating =======
== 20181126013131-fix-datalink-ordering.js: migrated (0.119s)
== 20181126013558-change-site-height-type.js (1.0.0): migrating =======
== 20181126013558-change-site-height-type.js: migrated (0.062s)
== 20181128123924-change-ucrm-id-column-to-text.js (1.0.0): migrating =======
== 20181128123924-change-ucrm-id-column-to-text.js: migrated (0.078s)
== 20181201102034-add-isp-column.js (1.0.0): migrating =======
== 20181201102034-add-isp-column.js: migrated (0.034s)
== 20181203093924-stations-count-device-statistics.js (1.0.0): migrating =======
== 20181203093924-stations-count-device-statistics.js: migrated (0.04s)
== 20181205115544-set-default-country.js (1.0.0): migrating =======
== 20181205115544-set-default-country.js: migrated (0.066s)
== 20181210114216-add-tokens.js (1.0.0): migrating =======
== 20181210114216-add-tokens.js: migrated (0.08s)
== 20181211084317-add-capacity-statistics.js (1.0.0): migrating =======
== 20181211084317-add-capacity-statistics.js: migrated (0.046s)
== 20181221020829-rename-esx-platform.js (1.0.0): migrating =======
== 20181221020829-rename-esx-platform.js: migrated (0.021s)
== 20181228035214-lldp-datalink-generation.js (1.0.0): migrating =======
== 20181228035214-lldp-datalink-generation.js: migrated (0.159s)
== 20190104095708-add-user-firstname-lastname.js (1.0.0): migrating =======
== 20190104095708-add-user-firstname-lastname.js: migrated (0.025s)
== 20190107050730-fix-firmware-batch-view.js (1.0.0): migrating =======
== 20190107050730-fix-firmware-batch-view.js: migrated (0.039s)
== 20190108105651-add-signal-statistics.js (1.0.0): migrating =======
== 20190108105651-add-signal-statistics.js: migrated (0.033s)
== 20190110010119-add-regulatory-domain-to-site.js (1.0.0): migrating =======
== 20190110010119-add-regulatory-domain-to-site.js: migrated (0.02s)
== 20190114043559-add-table-gateways.js (1.0.0): migrating =======
== 20190114043559-add-table-gateways.js: migrated (0.062s)
== 20190116025542-add-suspend-site-and-site-qos-table.js (1.0.0): migrating =======
== 20190116025542-add-suspend-site-and-site-qos-table.js: migrated (0.027s)
== 20190121032516-add-deleted-sites-table.js (1.0.0): migrating =======
== 20190121032516-add-deleted-sites-table.js: migrated (0.056s)
== 20190124094711-add-ccq-statistics.js (1.0.0): migrating =======
== 20190124094711-add-ccq-statistics.js: migrated (0.034s)
== 20190130153222-cleanup-and-make-constaints-deferrable.js (1.0.0): migrating =======
== 20190130153222-cleanup-and-make-constaints-deferrable.js: failed =======
{ error: constraint "gateway_device_id_fkey" of relation "gateway" does not exist
    at Connection.parseE (/home/app/unms/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/app/unms/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/app/unms/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 142,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '9189',
  routine: 'ATExecAlterConstraint' }
Migration failed: Error: Migration 20190130153222-cleanup-and-make-constaints-deferrable.js failed (0.02s): constraint "gateway_device_id_fkey" of relation "gateway" does not exist
    at Migrator.runMigrations (/home/app/unms/lib/dal/migrator/index.js:102:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Relevant logs from the UCRM container:
```
su-exec nginx /usr/src/ucrm/scripts/migrate.sh
{"message":"Start replace shared views.","channel":"migrate.sh","datetime":"2020-11-11T20:26:28+0100","severity":"INFO","level":200}
{"message":"Done replace shared views.","channel":"migrate.sh","datetime":"2020-11-11T20:26:29+0100","severity":"INFO","level":200}
{"message":"Start database migration.","channel":"migrate.sh","datetime":"2020-11-11T20:26:29+0100","severity":"INFO","level":200}
{"message":"Done database migration.","channel":"migrate.sh","datetime":"2020-11-11T20:26:55+0100","severity":"INFO","level":200}
{"message":"Start shared views migration.","channel":"migrate.sh","datetime":"2020-11-11T20:26:55+0100","severity":"INFO","level":200}
{"message":"Done shared views migration.","channel":"migrate.sh","datetime":"2020-11-11T20:26:56+0100","severity":"INFO","level":200}
{"message":"Start notification templates migration.","channel":"migrate.sh","datetime":"2020-11-11T20:26:56+0100","severity":"INFO","level":200}
{"message":"Done notification templates migration.","channel":"migrate.sh","datetime":"2020-11-11T20:26:57+0100","severity":"INFO","level":200}
{"message":"Bumping UNMS version from ENV variable to database.","channel":"migrate.sh","datetime":"2020-11-11T20:26:57+0100","severity":"INFO","level":200}
{"message":"Done bumping UNMS version from ENV variable to database.","channel":"migrate.sh","datetime":"2020-11-11T20:26:58+0100","severity":"INFO","level":200}
su-exec nginx /usr/src/ucrm/scripts/database_migrations_ready.sh
{"message":"Waiting for migrations.","channel":"database_migrations_ready.sh","datetime":"2020-11-11T20:26:58+0100","severity":"INFO","level":200}
{"message":"Waiting for migrations (20200826113244). Last successful migration version: 20200826113244.","channel":"database_migrations_ready.sh","datetime":"2020-11-11T20:26:58+0100","severity":"INFO","level":200}
```

Since I'm using an external PostgreSQL server (I applied https://github.com/padhi-homelab/services/blob/master/unms/config/postgres/create-users.sh), my docker-compose file looks like:
```
version: '3'

services:
  netflow:
    image: padhihomelab/unms:netflow-1.2.7
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "2055:2055/udp"
    environment:
      TZ: Europe/Vienna

  nginx:
    image: padhihomelab/unms:nginx-1.2.7
    restart: unless-stopped
    volumes:
      - ./data/cert:/cert:rw
      - ./data/firmwares:/www/firmwares:rw
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      TZ: Europe/Vienna

  rabbitmq:
    image: rabbitmq:3.8-alpine
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq:rw
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbit channel_max 4096'
      TZ: Europe/Vienna

  redis:
    image: redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - ./data/redis:/data/db:rw
    command: redis-server --appendonly yes --dir /data/db/
    environment:
      TZ: Europe/Vienna

  siridb:
    image: padhihomelab/unms:siridb-1.2.7
    restart: unless-stopped
    volumes:
      - ./data/siridb:/var/lib/siridb:rw
    environment:
      TZ: Europe/Vienna

  ucrm:
    image: padhihomelab/unms:ucrm-1.2.7
    restart: unless-stopped
    command: server_with_migrate
    depends_on:
      - rabbitmq
      - nginx
    volumes:
      - ./data/ucrm:/data:rw
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5433
      POSTGRES_USER: ucrm
      POSTGRES_PASSWORD: ucrm
      POSTGRES_DB: unms
      POSTGRES_SCHEMA: ucrm
      UNMS_POSTGRES_SCHEMA: unms
      UNMS_BASE_URL: /v2.1
      UNMS_VERSION: 1.2.7
      TZ: Europe/Vienna

  unms:
    image: padhihomelab/unms:1.2.7
    restart: unless-stopped
    depends_on:
      - redis
      - siridb
      - rabbitmq
      - nginx
      - ucrm
    volumes:
      - ./data:/home/app/unms/data:rw
    ports:
      - "3478:3478/udp"   # STUN
      - "6789:6789/tcp"   # Speed test
      - "8080:8080/tcp"   # Device/ controller comm.
      - "8443:8443/tcp"   # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp"   # HTTP portal redirection
      - "8843:8843/tcp"   # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    environment:
      UNMS_PG_HOST: postgresql
      UNMS_PG_PORT: 5433
      UNMS_PG_USER: unms
      UNMS_PG_PASSWORD: unms
      UNMS_PG_DB: unms
      UNMS_PG_SCHEMA: unms
      TZ: Europe/Vienna
    cap_add:
      - NET_ADMIN
```

Did you encounter this problem before or do you have an idea why a migration (I suppose even an older one) gives problems now?

**Comment by muhlba91** [comment]
Closing this issue. UNMS seems to have a hard requirement on PostgreSQL 9.6 which causes those errors to happen.

**Comment by SaswatPadhi** [comment]
Hi @muhlba91!

Sorry about the late response -- I must have missed the notification somehow. 

Yes, UNMS requires PostgreSQL 9.6. I had tested various versions of the other components (RabbitMQ, nginx, Redis, SiriDB) and used the latest versions that seemed to work.

I am upgrading this repo to version `1.3.0` (which was released yesterday) and will let you know if that works with PostgreSQL.
